"""add has_restarted to records

Revision ID: 11379fce0171
Revises: 22879c38beaa
Create Date: 2025-10-07 19:37:39.099791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11379fce0171'
down_revision: Union[str, Sequence[str], None] = '22879c38beaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('has_restarted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'has_restarted')
    # ### end Alembic commands ###
